namespace ProtonPassCliExtension.PassCli;

/// <summary>Non-secret fields for a new login. The password is generated by pass-cli itself.</summary>
internal sealed record NewLogin(
    string Title,
    string? VaultShareId,
    string? VaultName,
    string? Username,
    string? Email,
    string? Url);
