using System;
using System.ComponentModel;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.CommandPalette.Extensions;
using Microsoft.CommandPalette.Extensions.Toolkit;
using ProtonPassCliExtension.PassCli;
using ProtonPassCliExtension.Services;

namespace ProtonPassCliExtension.Pages;

internal sealed partial class CreateLoginPage : ContentPage
{
    private readonly CreateLoginForm _form;

    public CreateLoginPage(AppServices services)
    {
        _form = new CreateLoginForm(services);
        Name = "Create";
        Title = "New Proton Pass login";
        Icon = new IconInfo("");
    }

    public override IContent[] GetContent()
    {
        _form.Rebuild();
        return [_form];
    }
}

/// <summary>
/// Collects non-secret fields only. The password is generated by pass-cli (--generate-password),
/// so it never passes through this extension or a command line.
/// </summary>
internal sealed partial class CreateLoginForm : FormContent
{
    private readonly AppServices _services;

    public CreateLoginForm(AppServices services)
    {
        _services = services;
        Rebuild();
    }

    public void Rebuild()
    {
        var vaults = _services.Cache.Peek()
            .Select(i => (i.ShareId, i.VaultName))
            .Distinct()
            .OrderBy(v => v.VaultName, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        var body = new JsonArray { Text("title", "Title", required: true) };

        if (vaults.Count > 0)
        {
            var choices = new JsonArray();
            foreach (var (shareId, name) in vaults)
            {
                choices.Add(new JsonObject { ["title"] = name, ["value"] = shareId });
            }

            body.Add(new JsonObject
            {
                ["type"] = "Input.ChoiceSet",
                ["id"] = "vaultShareId",
                ["label"] = "Vault",
                ["style"] = "compact",
                ["value"] = vaults[0].ShareId,
                ["choices"] = choices,
            });
        }
        else
        {
            body.Add(Text("vaultName", "Vault name", required: true));
        }

        body.Add(Text("username", "Username"));
        body.Add(Text("email", "Email"));
        body.Add(Text("url", "Website URL"));
        body.Add(new JsonObject
        {
            ["type"] = "TextBlock",
            ["text"] = "A strong password is generated by Proton Pass CLI. It is not shown here; copy it from the item list.",
            ["wrap"] = true,
            ["isSubtle"] = true,
        });

        var card = new JsonObject
        {
            ["$schema"] = "http://adaptivecards.io/schemas/adaptive-card.json",
            ["type"] = "AdaptiveCard",
            ["version"] = "1.6",
            ["body"] = body,
            ["actions"] = new JsonArray { new JsonObject { ["type"] = "Action.Submit", ["title"] = "Create login" } },
        };

        TemplateJson = card.ToJsonString();
    }

    public override CommandResult SubmitForm(string payload)
    {
        JsonObject? input;
        try
        {
            input = JsonNode.Parse(payload)?.AsObject();
        }
        catch (JsonException)
        {
            input = null;
        }

        var title = input?["title"]?.ToString().Trim();
        if (input is null || string.IsNullOrEmpty(title))
        {
            StatusReporter.Show("A title is required.", MessageState.Warning);
            return CommandResult.KeepOpen();
        }

        var shareId = input["vaultShareId"]?.ToString();
        var vaultName = input["vaultName"]?.ToString().Trim();
        if (string.IsNullOrEmpty(shareId) && string.IsNullOrEmpty(vaultName))
        {
            StatusReporter.Show("Choose or enter a vault.", MessageState.Warning);
            return CommandResult.KeepOpen();
        }

        var login = new NewLogin(
            title,
            string.IsNullOrEmpty(shareId) ? null : shareId,
            string.IsNullOrEmpty(vaultName) ? null : vaultName,
            input["username"]?.ToString(),
            input["email"]?.ToString(),
            input["url"]?.ToString());

        try
        {
            var result = _services.Client.CreateLoginAsync(login).GetAwaiter().GetResult();
            if (!result.IsSuccess)
            {
                StatusReporter.Show(result.Error!);
                return CommandResult.KeepOpen();
            }
        }
        catch (Exception ex) when (ex is InvalidOperationException or Win32Exception)
        {
            StatusReporter.Show($"Create login failed: {ex.Message}");
            return CommandResult.KeepOpen();
        }

        // The list sees an empty cache next time it is shown and reloads, picking up the new item.
        _services.Cache.Invalidate();
        StatusReporter.Hide();
        return CommandResult.ShowToast("Login created with a generated password");
    }

    private static JsonObject Text(string id, string label, bool required = false)
    {
        var field = new JsonObject { ["type"] = "Input.Text", ["id"] = id, ["label"] = label };
        if (required)
        {
            field["isRequired"] = true;
            field["errorMessage"] = label + " is required";
        }

        return field;
    }
}
